#------------------------------------------------------------------------------
#
# Filename: aws-sandbox-bff-build-push.yml
#
# Description: Build and push MoneyMoov for Business BFF image to Azure Container Registry
#              https://docs.microsoft.com/azure/devops/pipelines/languages/docker
#
# Usage: run from devops pipeline
#
# Author: Axel Granillo (axel@nofrixion.com)
#
# History:    
# 10 August     2023  Axel Granillo   Created, Mexico City, Mexico (from existing pipeline)
#-----------------------------------------------------------------------------

# Don't run pipeline on PR
pr: none
trigger: none

variables:
  dockerfilePath: 'nofrixion.business/bff/NoFrixion.Bff/Dockerfile-devops'
  tag: $(Build.SourceBranchName)
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

resources:
  repositories:
  - repository: nofrixion.business.cicd
    type: bitbucket
    endpoint: Bitbucket-AaronAppPassword
    name: nofrixion/nofrixion.business.cicd
    ref: $(Build.SourceBranch)
  - repository: moneymoov-dotnet-sdk
    type: github
    endpoint: github.com_sipsorcery
    name: nofrixion/moneymoov-dotnet
    ref: $(Build.SourceBranch)
  - repository: nofrixion.common
    type: bitbucket
    endpoint: Bitbucket-AaronAppPassword
    name: nofrixion/nofrixion.common
    ref: $(Build.SourceBranch)


pool:
  vmImage: $(vmImageName)

steps:
- checkout: self
  fetchDepth: 1

- checkout: nofrixion.business.cicd
  fetchDepth: 1

- checkout: moneymoov-dotnet-sdk
  fetchDepth: 1

- checkout: nofrixion.common
  fetchDepth: 1

- task: Docker@2
  displayName: Build container image
  inputs:
    command: build
    repository: $(imageRepository)
    dockerfile: $(dockerfilePath)
    buildContext: $(Build.Repository.LocalPath)
    arguments: '-f $(dockerfilePath) --build-arg buildId=$(Build.SourceVersion)'
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      $(tag)

- task: Docker@2
  displayName: Push image to container registry
  inputs:
    command: push
    repository: $(imageRepository)
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      $(tag)
