#------------------------------------------------------------------------------
#
# Filename: aws-dev-bff-build-push.yml
#
# Description: Build and push MoneyMoov for Business BFF image to DEV Azure Container Registry
#              https://docs.microsoft.com/azure/devops/pipelines/languages/docker
#
# Usage: run from devops pipeline
#
# Author: Axel Granillo (axel@nofrixion.com)
#
# History:    
# 10 August     2023  Axel Granillo   Created, Mexico City, Mexico (from existing pipeline)
#-----------------------------------------------------------------------------

# Don't run pipeline on PR
pr: none 
trigger:
  - develop

variables:
  dockerfilePath: 'nofrixion.business/bff/NoFrixion.Bff/Dockerfile-devops'
  kustomizeOverlayPath: 'nofrixion.business.cicd/kubernetes/bff/overlays-aws/dev/'
  # Gives option to automate and run 'develop' tag in DEV, moov-X.XX tags in sandbox/prod
  tag: $(Build.SourceBranchName)
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

resources:
  repositories:
  - repository: nofrixion.business.cicd
    type: bitbucket
    endpoint: Bitbucket-AaronAppPassword
    name: nofrixion/nofrixion.business.cicd
    ref: develop
  - repository: moneymoov-dotnet-sdk
    type: github
    endpoint: github.com_sipsorcery
    name: nofrixion/moneymoov-dotnet
    ref: develop
  - repository: nofrixion.common
    type: bitbucket
    endpoint: Bitbucket-AaronAppPassword
    name: nofrixion/nofrixion.common
    ref: develop

pool:
  vmImage: $(vmImageName)

steps:
- checkout: self
  fetchDepth: 1

- checkout: nofrixion.business.cicd
  fetchDepth: 1

- checkout: moneymoov-dotnet-sdk
  fetchDepth: 1

- checkout: nofrixion.common
  fetchDepth: 1

- task: Docker@2
  name: imageBuild
  displayName: Build container image
  inputs:
    command: build
    repository: $(imageRepository)
    dockerfile: $(dockerfilePath)
    buildContext: $(Build.Repository.LocalPath)
    arguments: '-f $(dockerfilePath) --build-arg buildId=$(Build.SourceVersion)'
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      $(tag)

- task: Docker@2
  name: imagePush
  displayName: Push image to container registry
  inputs:
    command: push
    repository: $(imageRepository)
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      $(tag)

- task: AWSShellScript@1
  displayName: Run kubectl
  inputs:
    awsCredentials: $(k8sServiceConnection)
    regionName: $(awsEksRegion)
    scriptType: inline
    failOnStandardError: true
    inlineScript: |
      # suggested 'error handling' as per https://sipb.mit.edu/doc/safe-shell/
      set -euo pipefail      
      aws sts get-caller-identity
      aws eks update-kubeconfig --region $(awsEksRegion) --name $(clusterName) --role-arn "$(awsEksRoleArn)"
      # Run kubectl command
      kubectl get namespaces
      echo
      echo -e "Compiling k8s kustomize manifests...\n"
      kubectl kustomize $(kustomizeOverlayPath)
      echo
      echo -e "Applying kustomized manifests...\n"
      kubectl apply -k $(kustomizeOverlayPath) && echo "...OK"
      echo "Restarting deployment ..."
      kubectl rollout restart deployment/$(deploymentName) -n $(clusterNamespace)
